### PR TITLE
secret build type: use unique image name

### PR DESCRIPTION
**Pull request by TomasTomecek**
This is used to construct unique tag for image.

@mmilata can you review and merge please?

### CODE REVIEW

**Comment by mmilata** [comment]
Looks good but my openshift instance seems to ignore the :tag ... let me investigate a bit.

**Comment by mmilata** [comment]
The build json has the tag but openshift 1.0.0 seems to ignore it (so the image is tagged as latest). Merging this anyway since it's still an improvement over the previous behaviour.

**Comment by TomasTomecek** [comment]
Oh boy, we should definitely track the regression. Thanks for doing the merges Martin.

**Comment by mmilata** [comment]
Opened #149 for that.

**Pull request merged**
