### PR TITLE
BuildResponse: build_id property is unused

### PR DESCRIPTION
**Pull request by twaugh**
For identical functionality use get_build_name() method.

### CODE REVIEW

**Comment by TomasTomecek** [comment]
we need to be sure that @pbabinca is not using it in container build plugin

**Comment by twaugh** [comment]
The CLI was using it. Fixed.

**Comment by pbabinca** [comment]
I've fixed that in koji containerbuild plugin: https://github.com/release-engineering/koji-containerbuild/commit/b135f6df8edd2240bcebf3a9d0ae7d3793df924f too.

**Comment by pbabinca** [comment]
I've fixed that in koji containerbuild plugin: https://github.com/release-engineering/koji-containerbuild/commit/b135f6df8edd2240bcebf3a9d0ae7d3793df924f too.

**Comment by TomasTomecek** [comment]
Great, so let's merge then.

**Pull request merged**
